// a4: Campaign Brief Drafting
// Turns the intake classification into a one-page brief (objective, audience, messaging,
// KPIs, asset list, timeline) and attaches it as an Asana comment on the intake task.
// Uses claude-sonnet-4-6 (default tier) per §4 model tiering.

import { schemaTask } from "@trigger.dev/sdk";
import { BriefDraftingPayloadSchema } from "../ai/schemas.js";
import type { BriefDraftingPayload } from "../ai/schemas.js";
import { reason, MODELS } from "../ai/claude.js";
import { addTaskComment } from "../lib/asana.js";
import { logDecision } from "../lib/airtable.js";

function buildBriefPrompt(payload: BriefDraftingPayload): string {
  const { classification, sfCampaignId } = payload;
  // §6.6 brief inputs
  return `You are an expert B2B marketing strategist. Write a concise one-page campaign brief based on the intake data below.

CAMPAIGN INTAKE:
  Name:        ${payload.asanaTaskId} (Asana task)
  Type:        ${classification.type}
  Region:      ${classification.region}
  Quarter:     ${classification.quarter}
  Go-live:     ${classification.goLiveDate}
  Goal:        ${classification.goal ?? "not specified"}
  Audience:    ${classification.audience ?? "not specified"}
  Key message: ${classification.keyMessage ?? "not specified"}
  Budget:      ${classification.budget ?? "not specified"}
  SF Campaign: ${sfCampaignId ?? "pending"}

Write the brief using EXACTLY this structure (markdown headers):

## Objective
One sentence: what this campaign must achieve and how success is measured.

## Audience
Who we are targeting and why they care about this message.

## Messaging
The single key message and 2–3 supporting proof points.

## KPIs
3–5 measurable success metrics (e.g. registrations, MQLs, pipeline influenced).

## Asset Plan
Bulleted list of the assets that need to be produced (derive from the ${classification.type} type).

## Timeline
Key milestones from kickoff to go-live (${classification.goLiveDate}), with approximate dates.

Keep the entire brief under 400 words. No filler phrases.`;
}

export const a4BriefDrafting = schemaTask({
  id: "a4-brief-drafting",
  schema: BriefDraftingPayloadSchema,
  retry: { maxAttempts: 3, factor: 2, minTimeoutInMs: 2000, maxTimeoutInMs: 30_000 },

  run: async (payload: BriefDraftingPayload) => {
    const { asanaTaskId } = payload;

    const prompt = buildBriefPrompt(payload);
    const brief = await reason(prompt, 1024);

    // Attach to Asana task as a comment (simplest; no file-upload dependency)
    const comment =
      `📋 **Campaign Brief — Auto-generated by MOps AI**\n\n${brief}\n\n` +
      `_Generated by claude-sonnet-4-6. Review and adjust before sharing externally._`;
    await addTaskComment(asanaTaskId, comment);

    // TODO: Also attach brief to SF campaign via SF ContentVersion / ContentDocumentLink API
    //   once SF credentials are confirmed live. Requires:
    //     POST /sobjects/ContentVersion  { Title, PathOnClient, VersionData (base64), FirstPublishLocationId: sfCampaignId }

    await logDecision(asanaTaskId, {
      taskId:     asanaTaskId,
      automation: "a4-brief-drafting",
      decision:   "brief-generated",
      model:      MODELS.default,
      timestamp:  new Date().toISOString(),
      data: {
        type:       payload.classification.type,
        sfCampaignId: payload.sfCampaignId,
        wordCount:  brief.split(/\s+/).length,
      },
    });

    return { ok: true, briefGenerated: true };
  },
});
